import { BuiltInServiceId } from '../services.system'
import { audiobookshelf } from './audiobookshelf'
import { dozzle } from './dozzle'
import { jellyfin } from './jellyfin'
import { readeck } from './readeck'
import { DataLoader } from './types'

const dataLoaders: DataLoader<BuiltInServiceId, object> = {
  ...audiobookshelf,
  'adguard-home': undefined,
  authelia: undefined,
  authentik: undefined,
  bentopdf: undefined,
  bookstack: undefined,
  'calibre-web': undefined,
  changedetection: undefined,
  cup: undefined,
  ...dozzle,
  'firefly-iii': undefined,
  forgejo: undefined,
  freshrss: undefined,
  gitea: undefined,
  grafana: undefined,
  grimmory: undefined,
  'home-assistant': undefined,
  immich: undefined,
  ...jellyfin,
  karakeep: undefined,
  kavita: undefined,
  linkace: undefined,
  linkding: undefined,
  linkwarden: undefined,
  mealie: undefined,
  memos: undefined,
  miniflux: undefined,
  navidrome: undefined,
  nextcloud: undefined,
  ntfy: undefined,
  olivetin: undefined,
  otterwiki: undefined,
  paperless: undefined,
  papra: undefined,
  photoprism: undefined,
  'pi-hole': undefined,
  portainer: undefined,
  ...readeck,
  romm: undefined,
  ryot: undefined,
  seerr: undefined,
  shelfmark: undefined,
  'stirling-pdf': undefined,
  syncthing: undefined,
  'synology-calendar': undefined,
  'synology-contacts': undefined,
  'synology-drive': undefined,
  'synology-dsm': undefined,
  'synology-photos': undefined,
  tandoor: undefined,
  vaultwarden: undefined,
  wakapi: undefined,
  wallabag: undefined,
  wanderer: undefined,
  'wg-easy': undefined,
  wikijs: undefined,
  yamtrack: undefined,
  'your-spotify': undefined,
}

export function getDataLoader(serviceId: BuiltInServiceId) {
  return dataLoaders[serviceId]
}
