name: Create Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  check-skip:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Skip CI check
        run: echo "Proceeding with workflow"

  generate-schema:
    needs: check-skip
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun ci

      - name: Generate schema.json
        run: bun gen:schema

      - name: Upload schema.json
        uses: actions/upload-artifact@v4
        with:
          name: schema
          path: schema.json

  build-and-release:
    needs: generate-schema
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install dependencies
        run: bun ci

      - name: 📱 Build Production APK
        if: github.event_name || github.event_name == 'push'
        run: |
          eas build --platform android --profile production --local --non-interactive --output=./app-release.apk
        env:
          NODE_ENV: production

      - name: Download schema.json
        uses: actions/download-artifact@v5
        with:
          name: schema

      - name: 📝 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./app-dev.apk
            ./app-release.apk
            ./schema.json
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit schema
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add schema.json
          git diff --cached --quiet && echo "schema.json didn't change, skipping commit" exit 0
          git commit -m "Update schema.json"
          git push
