name: Create/Update Release PR

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  update-release-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create/Update GitHub Release PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BODY=$(gh api --method POST -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2026-03-10" \
          /repos/${GITHUB_REPOSITORY}/releases/generate-notes \
            -f 'tag_name=main' \
            -f 'target_commitish=main' \
            -q .body)

          # Increase heading level by one
          INDENTED_BODY=$(printf '%s' "$BODY" | sed -E 's/^(#{1,6})([[:space:]]+)/#\1\2/')

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git switch -C release

          if [[ $BODY == *"Exciting New Features"* ]]; then
            echo "Features found, bumping minor version"
            # Without `--git-tag-version false` it would create a commit
            npm version minor --git-tag-version false
          else
            echo "No Features found, bumping patch version"
            # Without `--git-tag-version false` it would create a commit
            npm version patch --git-tag-version false
          fi

          VERSION=$(jq -r .version package.json)

          NEW_CHANGELOG_STRING=$(printf '%s\n\n%s\n\n' "## v${VERSION}" "${INDENTED_BODY}")

          printf '\n%s\n\n' "$NEW_CHANGELOG_STRING" > temp_changelog
          # Inserts after first line
          sed -i "/^# Changelog/r temp_changelog" CHANGELOG.md
          rm temp_changelog

          git add package.json
          git add CHANGELOG.md
          git commit -m "chore(main): ${VERSION} [release]"

          git push origin release --force

          PR_NUMBER=$(gh pr list --head $(git branch --show-current) --json number --jq '.[0].number')

          if [[ -z "$PR_NUMBER" ]]; then
            echo "No PR found. Creating one..."
            gh pr create --base main \
            --draft \
            --title "chore: ${VERSION} [release]" \
            --body "${BODY}" \
            --assignee "SebastianBr11"
          else
            echo "PR #$PR_NUMBER exists. Editing it..."
            gh pr edit $PR_NUMBER --title "chore: ${VERSION} [release]" \
            --body "
            - [ ] Bump version
            ${BODY}"
          fi
