name: Create/Update Release PR

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 📝 Create/Update GitHub Release Draft
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
